{"name": "Нельзя создать двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "@allure.title(\"Нельзя создать двух одинаковых курьеров\")\n    def test_duplicate_login_courier_registration():\n        first_courier = register_courier()\n    \n        # Пытаемся создать второго курьера с тем же логином\n        payload = {\n            \"login\": first_courier[\"login\"],\n            \"password\": \"password456\",\n            \"firstName\": \"Jane\"\n        }\n        response = requests.post('https://qa-scooter.praktikum-services.ru/api/v1/courier', data=payload)\n        assert response.status_code == 409\n>       assert response.json()[\"message\"] == \"Этот логин уже используется\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_courier_registration.py:33: AssertionError"}, "start": 1703686143019, "stop": 1703686143770, "uuid": "5763fb23-f1c7-420c-af1c-43e9f186fe2e", "historyId": "306a9cd74ea87a52b95ceea02f308c2d", "testCaseId": "306a9cd74ea87a52b95ceea02f308c2d", "fullName": "tests.test_courier_registration#test_duplicate_login_courier_registration", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_registration"}, {"name": "host", "value": "LAPTOP-1KK7H688"}, {"name": "thread", "value": "13980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_registration"}]}